config/routes.rb
Rails.application.routes.draw do
  get 'index/index'

  resources :orders

  resources :customers

  resources :order_statuses

  devise_for :users
  root :to => "index#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :orderStatus
  belongs_to :customer
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @customers = Customer.all
    respond_with(@customers)
  end

  def show
    respond_with(@customer)
  end

  def new
    @customer = Customer.new
    respond_with(@customer)
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    respond_with(@customer)
  end

  def update
    @customer.update(customer_params)
    respond_with(@customer)
  end

  def destroy
    @customer.destroy
    respond_with(@customer)
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:firstname, :secondname, :companyName, :phoneNumber)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/order_statuses_controller.rb
class OrderStatusesController < ApplicationController
  before_action :set_order_status, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @order_statuses = OrderStatus.all
    respond_with(@order_statuses)
  end

  def show
    respond_with(@order_status)
  end

  def new
    @order_status = OrderStatus.new
    respond_with(@order_status)
  end

  def edit
  end

  def create
    @order_status = OrderStatus.new(order_status_params)
    @order_status.save
    respond_with(@order_status)
  end

  def update
    @order_status.update(order_status_params)
    respond_with(@order_status)
  end

  def destroy
    @order_status.destroy
    respond_with(@order_status)
  end

  private
    def set_order_status
      @order_status = OrderStatus.find(params[:id])
    end

    def order_status_params
      params.require(:order_status).permit(:status, :content, :user_id, :updateDate)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:title, :content, :orderStatus_id, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/order_statuses_helper.rb
module OrderStatusesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :secondname %><br>
    <%= f.text_field :secondname %>
  </div>
  <div class="field">
    <%= f.label :companyName %><br>
    <%= f.text_field :companyName %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Secondname</th>
      <th>Companyname</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.firstname %></td>
        <td><%= customer.secondname %></td>
        <td><%= customer.companyName %></td>
        <td><%= customer.phoneNumber %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @customer.firstname %>
</p>

<p>
  <strong>Secondname:</strong>
  <%= @customer.secondname %>
</p>

<p>
  <strong>Companyname:</strong>
  <%= @customer.companyName %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @customer.phoneNumber %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/index/index.html.erb
<h1>Order Managment</h1>
<p>Welcome page :)</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrderManagment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-6">
		<h1>Order Managment</h1>
	</div>
	<div class="col-md-4">
		User panel
	</div>

</div>
<div class="row">
  <div class="col-md-2">
  	<ul class="nav nav-pills nav-stacked" role="tablist">
  	  <%= link_to "Orders", orders_path %>
  	  <%= link_to "Customers", customers_path %>
	 </ul>
  </div>
  <div class="col-md-8">
  	<%= yield %>
  </div>
</div>


</body>
</html>

app/views/order_statuses/_form.html.erb
<%= form_for(@order_status) do |f| %>
  <% if @order_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_status.errors.count, "error") %> prohibited this order_status from being saved:</h2>

      <ul>
      <% @order_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :updateDate %><br>
    <%= f.date_select :updateDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_statuses/edit.html.erb
<h1>Editing order_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_status %> |
<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/index.html.erb
<h1>Listing order_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Content</th>
      <th>User</th>
      <th>Updatedate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_statuses.each do |order_status| %>
      <tr>
        <td><%= order_status.status %></td>
        <td><%= order_status.content %></td>
        <td><%= order_status.user %></td>
        <td><%= order_status.updateDate %></td>
        <td><%= link_to 'Show', order_status %></td>
        <td><%= link_to 'Edit', edit_order_status_path(order_status) %></td>
        <td><%= link_to 'Destroy', order_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order status', new_order_status_path %>

app/views/order_statuses/new.html.erb
<h1>New order_status</h1>

<%= render 'form' %>

<%= link_to 'Back', order_statuses_path %>

app/views/order_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order_status.status %>
</p>

<p>
  <strong>Content:</strong>
  <%= @order_status.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @order_status.user %>
</p>

<p>
  <strong>Updatedate:</strong>
  <%= @order_status.updateDate %>
</p>

<%= link_to 'Edit', edit_order_status_path(@order_status) %> |
<%= link_to 'Back', order_statuses_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :orderStatus_id %><br>
    <%= f.text_field :orderStatus_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Orderstatus</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.title %></td>
        <td><%= order.content %></td>
        <td><%= order.orderStatus %></td>
        <td><%= order.customer %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @order.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @order.content %>
</p>

<p>
  <strong>Orderstatus:</strong>
  <%= @order.orderStatus %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>